### ISSUE TITLE
Error cargo-web deploy

### ISSUE THREAD

**Issue by artem-v-shamsutdinov** [gabisurita/fullstack-rust#2]
Thank you for putting this together!

I'm getting the following error when running carbo-web deploy on Ubuntu 18:

$ cargo-web deploy
error:     Updating git repository `https://github.com/gabisurita/uuid`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for a dependency on `uuid`

Caused by:
  Unable to update https://github.com/gabisurita/uuid?branch=upgrade-rand-0.5

Caused by:
  failed to find branch `upgrade-rand-0.5`

Caused by:
  cannot locate local branch 'upgrade-rand-0.5'; class=Reference (4); code=NotFound (-3)

Thanks, :)

**Comment by gabisurita** [comment]
Hi, thanks for reporting this.

Rand 0.5 has already been released so we can probably remove the backport and use the release version of uuid. I'll check this later and submit a patch.
